name: Parallel System Group @RUC
description: RUC
menu:
 - page: Home
   url: /index.html
 - page: Papers
   url: /papers.html
 - page: Research Projects
   url: /projects.html
 - page: Group Members
   url: /members.html
 - page: Activities
   url: /activities.html
 - page: Join us
   url: /joinUs.html
menu_external:
 - title: Github
   url: "https://github.com/fengzigroup?tab=repositories"

include:
  - _pages

mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: 
locale: en_US
